name: sbdd_env
channels:
  - pytorch
  - nvidia
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch >=2.0
  - pytorch-cuda=11.8
  - torchvision
  - torchaudio
  - pytorch-lightning >=2.0
  - pytorch_scatter
  - scikit-learn >=1.0
  - pandas >=2.0
  - numpy >=1.22
  - scipy >=1.8
  - matplotlib-base
  - seaborn
  - jupyterlab
  - medchem=2.0.5 # Missing from last edit
  - lilly-medchem-rules=1.0.1=hfc55251_1 # Missing from last edit
  - ipywidgets
  - openmm >=8.0
  - ambertools >=23
  - parmed
  - mdtraj
  - pdbfixer
  - openbabel
  - biopython=1.79 # Needs to be pinned to 1.79 
  - tqdm
  - requests
  - pyyaml
  - imageio
  - omegaconf
  - pip
  - pip:
    - posebusters >=0.3
    - streamlit >=1.30
    - tenacity >=8.0
    - wandb >=0.15
    - pandas>=2.0.0
    - numpy>=1.24.0
    - rdkit>=2024.9.6
    - plotly>=5.18.0
    - py3Dmol>=2.0.0
    - pathlib>=1.0.1
    - pillow>=10.0.0
    - matplotlib>=3.7.0
    - scikit-learn>=1.3.0 
